### ISSUE TITLE
Head of Heaps removed swapTexture

### ISSUE THREAD

**Issue by samyduc** [AustinEast/heaps-aseprite#7]
In Aseprite.hx, we use texture.swapTexture(tex); 
heaps-aseprite/git/src/aseprite/Aseprite.hx:247: characters 15-26 : h3d.mat.Texture has no field swapTexture

Heaps removed the feature here:
https://github.com/HeapsIO/heaps/commit/51c6a622df69c4ddda6cbd82a41530b9c6b83bf0

**Comment by AustinEast** [comment]
Uh oh, thanks for the heads up! I'll look into a replacement solution 👍
